apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-custom-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-custom-controller
  template:
    metadata:
      labels:
        app: k8s-custom-controller
    spec:
      containers:
      - name: k8s-custom-controller
        image: opsclub/k8s_gitlab_webhook_controller:latest
        imagePullPolicy: Always
        env:
        - name: URL
          value: "https://gitlab.com/api/v4"
        - name: URL_PATH
          value: "/projects/PROJECT_ID/trigger/pipeline"
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: k8s-custom-controller
              key: gitlab.pipeline.tokens
      serviceAccountName: default
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-custom-controller
  namespace: kube-system
type: Opaque
data:
  gitlab.pipeline.tokens: 123
