apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: guestbook
  name: guestbook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: guestbook
  labels:
    app: guestbook
  annotations:
    image.update.trigger: "true"
    config.app/env: qualif
    config.app/branch: qualif
    config.app/project-id: "123456"
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: guestbook
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          failureThreshold: 10
          periodSeconds: 10
          timeoutSeconds: 10
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: LOGLEVEL
          value: INFO
        resources: null
